version: '3'
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=1234